<a href="https://colab.research.google.com/github/Existanze54/sirius-neural-networks-2025/blob/main/Seminars/S01_part2_PyTorch_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Нейронные сети в биоинформатике

### Семинар 1: Подборка задач

#### Задача 1

Создайте пустой тензор размера `(10,)`.

In [ ]:
import torch
x = torch.empty(10)
x

tensor([-9.9299e+05,  4.4742e-41, -9.9299e+05,  4.4742e-41,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  6.2121e+22])

#### Задача 2

Создайте тензор со значениями от 15 до 59.

In [ ]:
tensor2 = torch.arange(15, 60)
tensor2

tensor([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
        33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59])

#### Задача 3

Создайте тензор 5x5 со значениями от 100 до 124.

In [ ]:
tensor3 = torch.arange(100, 125).reshape(5, 5)
tensor3

tensor([[100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124]])

In [ ]:
tensor3.shape

torch.Size([5, 5])

#### Задача 4

Создайте единичную матрицу (тензор) размера 10.

In [ ]:
tensor4 = torch.eye(10)
tensor4

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

#### Задача 5

Создайте матрицу 10x20 со случайными значениями из нормального распределения. Найдите минимум:

1. Глобально,
2. По строкам,
3. По столбцам.

In [ ]:
tensor5 = torch.randn(10, 20)
min_global = tensor5.min()
min_global.item()
min_rows = tensor5.min(axis = 1)
print(min_rows)
min_cols = tensor5.min(axis = 0)
print(min_cols[0][0])

torch.return_types.min(
values=tensor([-1.3263, -1.9047, -2.6638, -1.4624, -1.5380, -1.1616, -1.9660, -1.2897,
        -1.9532, -2.3272]),
indices=tensor([16,  1, 18,  6,  3,  2, 16,  1, 15, 18]))
-0.8041250705718994


#### Задача 6

Создайте тензор размера 32x32 из единиц, и заполните его края нулями.

In [ ]:
tensor6 = torch.ones(32, 32)
tensor6[:, [0, -1]] = 0
tensor6[[0, -1], :] = 0
tensor6

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 1.,  ..., 1., 1., 0.],
        [0., 1., 1.,  ..., 1., 1., 0.],
        ...,
        [0., 1., 1.,  ..., 1., 1., 0.],
        [0., 1., 1.,  ..., 1., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

#### Задача 7

Сгенерируйте случайный тензор размера 30x30. Добавьте к нему поля из нулей (размер станет 32x32).

In [ ]:
tensor7 = torch.rand(30, 30)
tensor_0 = torch.zeros(32, 32)
tensor_0[1:-1, 1:-1] = tensor7
tensor_0

tensor([[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.6114, 0.2404,  ..., 0.0089, 0.7439, 0.0000],
        [0.0000, 0.2879, 0.5999,  ..., 0.0412, 0.8312, 0.0000],
        ...,
        [0.0000, 0.6976, 0.6192,  ..., 0.4554, 0.1465, 0.0000],
        [0.0000, 0.7089, 0.8203,  ..., 0.7426, 0.3252, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]])

#### Задача 8

Создайте тензор 8x8 и заполните его 0 и 1 в шахматном порядке.

In [ ]:
tensor8 = torch.ones(8, 8)
tensor8[::2,::2] = 0
tensor8[1::2, 1::2] = 0
tensor8

tensor([[0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.]])

#### Задача 9

Создайте случайный тензор и отсортируйте его.

#### Задача 10

Сгенерируйте тензор из 100 случайных чисел из стандартного нормального распределения. Найдите в нем ближайшее число к 2.

#### Задача 11

Сгенерируйте 2 тензора размера `(30,)` - координаты 30 точек в двумерном пространстве. Найдите матрицу попарных расстояний для этих точек.

#### Задача 12

Создайте случайный двумерный тензор произвольного размера. Вычтите из каждой строки ее среднее.

#### Задача 13

Создайте одномерный тензор длины 100, числа в котором формируют "пилу" периода 10.

Пример "пилы" периода 3: `[1, 2, 3, 1, 2, 3, 1, 2, 3, ...]`

#### Задача 14

Создайте "пилу" длины 99 с периодом 10. Сделайте из нее тензор размера 11x9 и отсортируйте его по 2 колонке.

#### Задача 15

Посчитайте средние четырехмерного массива сразу по двум последним измерениям.

#### Задача 16*

Сгенерируйте тензор произвольной длины (более 100) и посчитайте средние в нем по окну размера 5.